### ISSUE TITLE
Failed to build in go 1.8

### ISSUE THREAD

**Issue by jvsteiner** [tecbot/gorocksdb#78]
After upgrading to go 1.8 (release) on OSX, I receive the following error at compile time in a project that uses `gorocksdb`:

```Undefined symbols for architecture x86_64:
  "_rocksdb_options_set_allow_os_buffer", referenced from:
      __cgo_9a8809814800_Cfunc_rocksdb_options_set_allow_os_buffer in options.cgo2.o
     (maybe you meant: __cgo_9a8809814800_Cfunc_rocksdb_options_set_allow_os_buffer)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jvsteiner** [comment]
### Update
pulled latest from repo, and used `brew switch rocksdb 5.1.2` to use latest rocksdb.  that fixed it all.
